heat_template_version: wallaby

parameters:
  # Set these via parameter defaults to configure external VIPs
  ControlPlaneIP:
    default: ''
    type: string
  InternalApiNetworkVip:
    default: ''
    type: string
  StorageNetworkVip:
    default: ''
    type: string
  StorageMgmtNetworkVip:
    default: ''
    type: string
  # The following are unused in this template
  ControlPlaneIp:
    default: ''
    type: string
  ControlPlaneSubnetCidr: # Here for compatibility with ctlplane_vip.yaml
    default: ''
    description: >
      The subnet CIDR of the control plane network. (The parameter is
      automatically resolved from the ctlplane subnet's cidr attribute.)
    type: string
  InternalApiIp:
    default: ''
    type: string
  InternalApiIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageIp:
    default: ''
    type: string
  StorageIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageMgmtIp:
    default: ''
    type: string
  StorageMgmtIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value:
      ctlplane: {get_param: ControlPlaneIP}
      ctlplane_uri:
        str_replace:
          template:
            make_url:
              host: {get_param: ControlPlaneIP}
          params:
            //: ''
      internal_api: {get_param: InternalApiNetworkVip}
      internal_api_uri:
        str_replace:
          template:
            make_url:
              host: {get_param: InternalApiNetworkVip}
          params:
            //: ''
      storage: {get_param: StorageNetworkVip}
      storage_uri:
        str_replace:
          template:
            make_url:
              host: {get_param: StorageNetworkVip}
          params:
            //: ''
      storage_mgmt: {get_param: StorageMgmtNetworkVip}
      storage_mgmt_uri:
        str_replace:
          template:
            make_url:
              host: {get_param: StorageMgmtNetworkVip}
          params:
            //: ''