apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNetConfig
metadata:
  name: openstacknetconfig-new
spec:
  attachConfigurations:
    br-internal:
      nodeNetworkConfigurationPolicy:
        nodeSelector:
          node-role.kubernetes.io/master: ""
        desiredState:
          interfaces:
          - bridge:
              options:
                stp:
                  enabled: false
              port:
              - name: eno12409
            description: Linux bridge with eno12409 as a port
            name: br-internal
            state: up
            type: linux-bridge
            mtu: 1500
          - name: eno12409
            type: ethernet
            state: up
            mtu: 1500
  dnsServers:
  - 192.168.131.20
 # optional DnsSearchDomains list
  dnsSearchDomains:
  - turbo.lab.test
  domainName: turbo.lab.test
  networks:
  - name: InternalApi
    nameLower: internal_api
    mtu: 1400
    subnets:
    - name: internal_api
      vlan: 3802
      ipv4:
        allocationEnd: 172.16.2.50
        allocationStart: 172.16.2.10
        cidr: 172.16.2.0/24
      attachConfiguration: br-internal
  - name: Control
    nameLower: ctlplane
    subnets:
    - name: ctlplane
      ipv4:
        allocationEnd: 192.168.131.100
        allocationStart: 192.168.131.60
        cidr: 192.168.131.0/25
        gateway: 192.168.131.1
      attachConfiguration: br-internal
  - name: Storage
    nameLower: storage
    mtu: 1400
    subnets:
    - name: storage
      ipv4:
        allocationEnd: 172.16.4.50
        allocationStart: 172.16.4.10
        cidr: 172.16.4.0/24
      vlan: 3804
      attachConfiguration: br-internal
  - name: StorageMgmt
    nameLower: storage_mgmt
    mtu: 1400
    subnets:
    - name: storage_mgmt
      ipv4:
        allocationEnd: 172.16.5.50
        allocationStart: 172.16.5.10
        cidr: 172.16.5.0/24
      vlan: 3805
      attachConfiguration: br-internal
  - name: Tenant
    nameLower: tenant
    vip: False
    mtu: 1400
    subnets:
    - name: tenant
      ipv4:
        allocationEnd: 172.16.3.50
        allocationStart: 172.16.3.10
        cidr: 172.16.3.0/24
      vlan: 3803
      attachConfiguration: br-internal

