resource_registry:
  OS::TripleO::Server: ../deployed-server/deployed-server.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: OS::Neutron::Port


  OS::TripleO::Controller::Net::SoftwareConfig: OS::Heat::None

  OS::TripleO::ComputeHCI::Net::SoftwareConfig: OS::Heat::None


parameter_defaults:
  EnablePackageInstall: True

  ControllerNetworkConfigTemplate: 'templates/net_config_static_bridge.j2'

  ComputeHCINetworkConfigTemplate: 'templates/net_config_static_bridge.j2'
