- {}
- config_image: registry.redhat.io/rhosp-rhel9/openstack-cinder-api:17.1.6
  config_volume: cinder
  puppet_tags: cinder_config,file,concat,file_line,cinder_api_paste_ini
  step_config: 'include tripleo::profile::base::cinder::api

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-cinder-api:17.1.6
  config_volume: cinder
  puppet_tags: cinder_config,file,concat,file_line
  step_config: 'include tripleo::profile::base::cinder::scheduler


    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-cinder-api:17.1.6
  config_volume: cinder
  puppet_tags: cinder_config,file,concat,file_line
  step_config: 'include tripleo::profile::base::lvm

    include tripleo::profile::pacemaker::cinder::volume_bundle

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-mariadb:17.1.6
  config_volume: clustercheck
  puppet_tags: file
  step_config: include tripleo::profile::pacemaker::clustercheck
- config_image: registry.redhat.io/rhosp-rhel9/openstack-glance-api:17.1.6
  config_volume: glance_api
  puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config,glance_image_import_config
  step_config: 'include tripleo::profile::base::glance::api

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-glance-api:17.1.6
  config_volume: glance_api_internal
  puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config,glance_image_import_config
  step_config: "class { 'tripleo::profile::base::glance::api':\n  bind_port => 9293,\n\
    \  tls_proxy_port => 9293,\n  log_file => '/var/log/glance/api_internal.log',\n\
    \  show_image_direct_url => true,\n  show_multiple_locations => true,\n}\n\ninclude\
    \ tripleo::profile::base::database::mysql::client"
- config_image: registry.redhat.io/rhosp-rhel9/openstack-haproxy:17.1.6
  config_volume: haproxy
  puppet_tags: haproxy_config
  step_config: 'exec {''wait-for-settle'': command => ''/bin/true'' }

    class tripleo::firewall(){}; define tripleo::firewall::rule( $port = undef, $dport
    = undef, $sport = undef, $proto = undef, $action = undef, $state = undef, $source
    = undef, $iniface = undef, $chain = undef, $destination = undef, $extras = undef){}

    [''pcmk_bundle'', ''pcmk_resource'', ''pcmk_property'', ''pcmk_constraint'', ''pcmk_resource_default''].each
    |String $val| { noop_resource($val) }

    include tripleo::profile::pacemaker::haproxy_bundle'
  volumes: []
- config_image: registry.redhat.io/rhosp-rhel9/openstack-heat-api:17.1.6
  config_volume: heat_api
  puppet_tags: heat_config,file,concat,file_line,heat_api_paste_ini
  step_config: 'include tripleo::profile::base::heat::api

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-heat-api-cfn:17.1.6
  config_volume: heat_api_cfn
  puppet_tags: heat_config,file,concat,file_line
  step_config: 'include tripleo::profile::base::heat::api_cfn

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-heat-api:17.1.6
  config_volume: heat
  puppet_tags: heat_config,file,concat,file_line
  step_config: 'include tripleo::profile::base::heat::engine

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-horizon:17.1.6
  config_volume: horizon
  puppet_tags: horizon_config
  step_config: 'include tripleo::profile::base::horizon

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-iscsid:17.1.6
  config_volume: iscsid
  puppet_tags: iscsid_config
  step_config: 'include tripleo::profile::base::iscsid

    '
  volumes:
  - /etc/iscsi:/tmp/iscsi.host:z
- config_image: registry.redhat.io/rhosp-rhel9/openstack-keystone:17.1.6
  config_volume: keystone
  puppet_tags: keystone_config,keystone_domain_config
  step_config: '[''Keystone_user'', ''Keystone_endpoint'', ''Keystone_domain'', ''Keystone_tenant'',
    ''Keystone_user_role'', ''Keystone_role'', ''Keystone_service''].each |String
    $val| { noop_resource($val) }

    include tripleo::profile::base::keystone


    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-memcached:17.1.6
  config_volume: memcached
  puppet_tags: file
  step_config: 'include tripleo::profile::base::memcached

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-mariadb:17.1.6
  config_volume: mysql
  puppet_tags: file
  step_config: '[''Mysql_datadir'', ''Mysql_user'', ''Mysql_database'', ''Mysql_grant'',
    ''Mysql_plugin''].each |String $val| { noop_resource($val) }

    exec {''wait-for-settle'': command => ''/bin/true'' }

    include tripleo::profile::pacemaker::database::mysql_bundle'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-neutron-server:17.1.6
  config_volume: neutron
  puppet_tags: neutron_config,neutron_api_paste_ini
  step_config: 'include tripleo::profile::base::neutron::server

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-neutron-server:17.1.6
  config_volume: neutron
  puppet_tags: neutron_plugin_ml2
  step_config: 'include tripleo::profile::base::neutron::plugins::ml2

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-nova-api:17.1.6
  config_volume: nova
  puppet_tags: nova_config,nova_api_paste_ini
  step_config: '[''Nova_cell_v2''].each |String $val| { noop_resource($val) }

    include tripleo::profile::base::nova::api

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-nova-api:17.1.6
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::conductor

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-nova-api:17.1.6
  config_volume: nova_metadata
  puppet_tags: nova_config,nova_api_paste_ini
  step_config: 'include tripleo::profile::base::nova::metadata

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-nova-api:17.1.6
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::scheduler

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-nova-api:17.1.6
  config_volume: nova
  puppet_tags: nova_config
  step_config: 'include tripleo::profile::base::nova::vncproxy

    include tripleo::profile::base::database::mysql::client'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-cron:17.1.6
  config_volume: crond
  step_config: include tripleo::profile::base::logging::logrotate
- config_image: registry.redhat.io/rhosp-rhel9/openstack-ovn-controller:17.1.6
  config_volume: ovn_controller
  puppet_tags: vs_config,exec
  step_config: 'include tripleo::profile::base::neutron::agents::ovn

    '
  volumes:
  - /lib/modules:/lib/modules:ro
  - /run/openvswitch:/run/openvswitch:shared,z
  - /etc/sysconfig/modules:/etc/sysconfig/modules
- config_image: registry.redhat.io/rhosp-rhel9/openstack-placement-api:17.1.6
  config_volume: placement
  puppet_tags: placement_config
  step_config: 'include tripleo::profile::base::database::mysql::client

    include tripleo::profile::base::placement::api'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-rabbitmq:17.1.6
  config_volume: rabbitmq
  puppet_tags: file,file_line
  step_config: '[''Rabbitmq_policy'', ''Rabbitmq_user''].each |String $val| { noop_resource($val)
    }

    include tripleo::profile::pacemaker::rabbitmq_bundle'
- config_image: registry.redhat.io/rhosp-rhel9/openstack-swift-proxy-server:17.1.6
  config_volume: swift
  puppet_tags: swift_config,swift_proxy_config,swift_keymaster_config
  step_config: 'include tripleo::profile::base::swift::proxy

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-swift-proxy-server:17.1.6
  config_volume: swift_ringbuilder
  puppet_tags: swift_config,exec,fetch_swift_ring_tarball,extract_swift_ring_tarball,ring_object_device,swift::ringbuilder::create,tripleo::profile::base::swift::add_devices,swift::ringbuilder::rebalance,create_swift_ring_tarball,upload_swift_ring_tarball
  step_config: 'include tripleo::profile::base::swift::ringbuilder

    '
- config_image: registry.redhat.io/rhosp-rhel9/openstack-swift-proxy-server:17.1.6
  config_volume: swift
  puppet_tags: swift_config,swift_container_config,swift_container_sync_realms_config,swift_account_config,swift_object_config,swift_object_expirer_config,rsync::server
  step_config: 'class xinetd() {}

    define xinetd::service($bind='''',$port='''',$server='''',$server_args='''') {}

    noop_resource(''service'')

    include tripleo::profile::base::swift::storage'
