collectd:
  collectd::plugin::ceph::daemons: []
  collectd::plugin::memcached::instances:
    local:
      host: '%{hiera(''memcached::listen_ip_uri'')}'
      port:
      - 11211
  tripleo.collectd.plugins.ceph_mon:
  - ceph
  tripleo.collectd.plugins.memcached:
  - memcached
mysql:
  cinder::db::mysql::dbname: cinder
  cinder::db::mysql::host: '%'
  cinder::db::mysql::password: 6hlkcpd9x7kl7thpsq5lxk2tx
  cinder::db::mysql::user: cinder
  glance::db::mysql::dbname: glance
  glance::db::mysql::host: '%'
  glance::db::mysql::password: 86dwpfj89wrpdp479fssqqhk5
  glance::db::mysql::user: glance
  heat::db::mysql::dbname: heat
  heat::db::mysql::host: '%'
  heat::db::mysql::password: js2mqvhzglh9x2wzlsfqwfpn9
  heat::db::mysql::user: heat
  keystone::db::mysql::dbname: keystone
  keystone::db::mysql::host: '%'
  keystone::db::mysql::password: kc48w9nf6hk5dcxbkvbkcqrwc
  keystone::db::mysql::user: keystone
  neutron::db::mysql::dbname: ovs_neutron
  neutron::db::mysql::host: '%'
  neutron::db::mysql::password: wgl94qxjvp5xr49xk2c5q7cjn
  neutron::db::mysql::user: neutron
  nova::db::mysql::dbname: nova
  nova::db::mysql::host: '%'
  nova::db::mysql::password: l8mtl7kxvm55px2l5nd8bbkmd
  nova::db::mysql::user: nova
  nova::db::mysql_api::dbname: nova_api
  nova::db::mysql_api::host: '%'
  nova::db::mysql_api::password: l8mtl7kxvm55px2l5nd8bbkmd
  nova::db::mysql_api::user: nova_api
  placement::db::mysql::dbname: placement
  placement::db::mysql::host: '%'
  placement::db::mysql::password: q858cqz76262h4rgnbtx4glsn
  placement::db::mysql::user: placement
pacemaker:
  keystone::admin_password: h5fxn4fxfqsszsmn9hlsb4ztd
  keystone::endpoint::admin_url: http://172.16.1.10:35357
  keystone::endpoint::internal_url: http://172.16.2.10:5000
  keystone::endpoint::public_url: http://192.168.131.60:5000
  keystone::endpoint::region: regionOne
rabbitmq:
  get_attr:
  - NovaBase
  - role_data
  - service_config_settings
  rabbitmq: null
rsyslog:
  tripleo_logging_sources_cinder_api:
  - file: /var/log/containers/cinder/cinder-api.log
    tag: openstack.cinder.api
  tripleo_logging_sources_cinder_scheduler:
  - file: /var/log/containers/cinder/cinder-scheduler.log
    tag: openstack.cinder.scheduler
  tripleo_logging_sources_cinder_volume:
  - file: /var/log/containers/cinder/cinder-volume.log
    tag: openstack.cinder.volume
  tripleo_logging_sources_glance_api:
  - file: /var/log/containers/glance/api.log
    tag: openstack.glance.api
  tripleo_logging_sources_glance_api_internal:
  - file: /var/log/containers/glance/api_internal.log
    tag: openstack.glance.api
  tripleo_logging_sources_haproxy:
  - file: /var/log/containers/haproxy/haproxy.log
    startmsg.regex: ^[a-zA-Z]{3} [0-9]{2} [:0-9]{8}
    tag: openstack.haproxy
  tripleo_logging_sources_heat_api:
  - file: /var/log/containers/heat/heat_api.log
    tag: openstack.heat.api
  tripleo_logging_sources_heat_api_cfn:
  - file: /var/log/containers/heat/heat_api_cfn.log
    tag: openstack.heat.api.cfn
  tripleo_logging_sources_heat_engine:
  - file: /var/log/containers/heat/heat-engine.log
    tag: openstack.heat.engine
  tripleo_logging_sources_horizon:
  - file: /var/log/containers/horizon/horizon.log
    tag: openstack.horizon
  tripleo_logging_sources_keystone:
    file: /var/log/containers/keystone/keystone.log
    tag: openstack.keystone
  tripleo_logging_sources_neutron_api:
  - file: /var/log/containers/neutron/server.log
    tag: openstack.neutron.api
  tripleo_logging_sources_nova_api:
  - file: /var/log/containers/nova/nova-api.log
    tag: openstack.nova.api
  tripleo_logging_sources_nova_conductor:
  - file: /var/log/containers/nova/nova-conductor.log
    tag: openstack.nova.conductor
  tripleo_logging_sources_nova_metadata:
  - file: /var/log/containers/nova/nova-metadata-api.log
    tag: openstack.nova.api.metadata
  tripleo_logging_sources_nova_scheduler:
  - file: /var/log/containers/nova/nova-scheduler.log
    tag: openstack.nova.scheduler
  tripleo_logging_sources_nova_vnc_proxy:
  - file: /var/log/containers/nova/nova-novncproxy.log
    tag: openstack.nova.vncproxy
  tripleo_logging_sources_pacemaker:
  - file: /var/log/host/pacemaker/pacemaker.log
    startmsg.regex: ^[a-zA-Z]{3} [0-9]{2} [:0-9]{8}
    tag: system.pacemaker
  tripleo_logging_sources_placement:
  - file: /var/log/containers/httpd/placement_wsgi_error_ssl.log
    tag: openstack.placement
