- hosts: Undercloud
  name: External update step 0
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: 0
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_update_steps_tasks.yaml
  tags:
    - step0
    - external
    - external_update_steps
- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: Undercloud
  name: External update step 1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '1'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_update_steps_tasks.yaml
  tags:
    - step1
    - external
    - external_update_steps
- hosts: Undercloud
  name: External update step 2
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '2'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_update_steps_tasks.yaml
  tags:
    - step2
    - external
    - external_update_steps
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '1'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step1
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 2
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '2'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step2
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 3
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '3'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step3
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 4
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '4'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step4
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 5
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  become: false
  vars:
    bootstrap_server_id: 57536d10-1faf-4377-a332-3f9d87d9e400
    step: '5'
    deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step5
