- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: overcloud
  strategy: tripleo_free
  any_errors_fatal: yes
  tasks:
    - include_tasks: post_upgrade_steps_tasks.yaml
      with_sequence: start=0 end=3
      vars:
        bootstrap_server_id: 2c50483f-0cb6-4c45-95ce-59c5e573d3d0
        deploy_identifier: OSP_DIRECTOR_OPERATOR_DEPLOY_IDENTIFIER
        enable_debug: False
        enable_puppet: True
        container_cli: podman
        container_log_stdout_path: /var/log/containers/stdouts
        container_healthcheck_disabled: False
        docker_puppet_debug: False
        docker_puppet_process_count: 6
        docker_puppet_mount_host_puppet: True
      loop_control:
        loop_var: step
